name: UtilidadesPlus
version: '1.0.0'
main: com.sistemautil.SistemaUtil
api-version: '26.2'
author: donnie1337
description: Utilidades do servidor, incluindo MOTD e preferências de entrada/saída.
softdepend:
  - CargoPlus
commands:
  motdplus:
    description: Recarrega a configuração do MOTD.
    usage: /motdplus reload
    aliases:
      - motd
    permission: utilidadesplus.motd.admin
  configurar:
    description: Abre o menu de configuração das utilidades pessoais.
    usage: /configurar
    permission: utilidadesplus.configurar
permissions:
  utilidadesplus.motd.admin:
    description: Permite recarregar a configuração do MOTD.
    default: false
  utilidadesplus.configurar:
    description: Permite abrir o menu de configuração das utilidades pessoais.
    default: false
  utilidadesplus.plugins:
    description: Permite visualizar a lista de plugins do servidor.
    default: false
  utilidadesplus.admin:
    description: Permite visualizar o Tab Complete dos comandos internos /spigot e /bukkit.
    default: false
